### ISSUE TITLE
Missing AccessProtocol.1 section for most SEs

### ISSUE THREAD

**Issue by sfayer** [ic-hep/DIRAC#53]
Most of the SEs (primarily non-UK ones) added by the AutoBDII2CS agent are missing the AccessProtocol.1 section. It isn't clear exactly what's causing this, but it's probably just a slight difference in the way the information is published.

**Comment by marianne013** [comment]
Hi Alex, 

if you have some time could you concentrate on getting BNL-ATLAS[n]-disk and RAL-LACG2[n]-disk to work, as we have some customers and I would really prefer the lazy option to configuring these by hand.

Daniela

**Comment by alexanderrichards** [comment]
@sfayer My initial guess (before I've fully got my head back into what's going on) is that the following line is returning srmDict as an empty dict:
https://github.com/ic-hep/GridPPDIRAC/blob/master/ConfigurationSystem/private/AddResourceAPI.py#L446

could you dump the following at this point
```python
from pprint import pprint
print "SE:", se
pprint(srms)
```

you could actually only catch and dump some of the ones we are interested in rather than all of them with an `if se in [ ]`

**Comment by sfayer** [comment]
Hi @alexanderrichards

I presume you wanted me to pprint srmDict rather than srms, this is the result for some faulty SEs:
```
SE: dcache07.unl.edu
None
SE: dcsrm.usatlas.bnl.gov
None
SE: fg-bestman1.fnal.gov
None
SE: fndca1.fnal.gov
None
SE: gk03.atlas-swt2.org
None
SE: gk05.swt2.uta.edu
None
```
For the working ones, it prints a large dictionary with many BDII/GLUE fields; so it looks like your guess is good.

Regards,
Simon

**Comment by alexanderrichards** [comment]
@sfayer I think the above two fixes do what we need. Please can you run a test then merge them

**Comment by alexanderrichards** [comment]
@sfayer I have updated these three pull requests and the combination of all three should hopefully fix the issues (at least for the lsst vo that I've been testing)
