### ISSUE TITLE
[Web portal] Data -> Metadata Catalog throws an error

### ISSUE THREAD

**Issue by twhyntie** [ic-hep/DIRAC#57]
Hello,

Steve Lloyd and I have been exploring the web portal:

https://dirac.gridpp.ac.uk/DIRAC/

One feature that looks like it could be _really_useful is the **Data** &rightarrow; **Metadata Catalog** page:

https://dirac.gridpp.ac.uk/DIRAC/GridPP/gridpp_user/data/MetaCatalog/display

As it looks like it could be used to display the contents of the DFC via the web.

However, when I try to submit any sort of query I get the following error:

"_There is an exception while loading data. Please, refresh table_"

The last metadata-related problem involved a trivial fix setting a parameter - might this be the case here?

Thanks as ever, @twhyntie

**Comment by sfayer** [comment]
Hi,
That error is caused by the backend returning unexpected values when the result list is empty. The "Metadata query" pane doesn't work correctly; "Path to start from" must be set lower than '/' for any results to be returned, i.e. '/\<voname\>'. Even when you get results, they don't seem to be filtered at all by the parameters added to the query. There isn't much we can do about this at the moment, this web interface module isn't officially supported any more.
Regards,
@sfayer

**Comment by twhyntie** [comment]
Hi @sfayer,

Thanks for this - indeed the `/<voname>` does work as you say but without actually being able to use the metadata to filter results it's not particularly useful.

Is there a way to disable pages on the web interface that don't work? Having broken/non-functioning pages available is a bit confusing...

Thanks again, @twhyntie

**Comment by sfayer** [comment]
Hi,

There isn't really any way of us to disable this feature... If we were to manually patch it out of the code, it'd get re-enabled on the next update. The new web interface has an improved tool which replaces the "Metadata catalog" page although I don't know when we'll upgrade (other things have been moved around / changed so from a user perspective it'll be quite a major update).

Regards,
Simon
