### ISSUE TITLE
Can't submit to Brunel for some reason

### ISSUE THREAD

**Issue by sllloyd** [ic-hep/DIRAC#59]
What's wrong here? (using gridpp VO)
2016-03-02 11:23:56 UTC Framework/API  ERROR: >>>> Error in setDestination() <<<<
2016-03-02 11:23:56 UTC Framework/API  ERROR: Problem with DIRAC.Core.Base.API.setDestination() call:
2016-03-02 11:23:56 UTC Framework/API  ERROR: Arguments: destination = LCG.UKI-LT2-Brunel.uk ( <type 'str'> )
2016-03-02 11:23:56 UTC Framework/API  ERROR: Message: LCG.UKI-LT2-Brunel.uk is not a valid destination site
2016-03-02 11:23:56 UTC Framework/API  ERROR:

**Comment by sfayer** [comment]
Hi Steve,

This appears to be caused by a bug in our BDII import agent... We've temporarily fixed it pending a proper patch, so it should work now.

We're trying to build a community for our DIRAC users. Could you please ask questions like this on the gridpp-dirac-users list[*] first in the future? We're hoping that other people may find our answers useful that way...

[*] https://mailman.ic.ac.uk/mailman/listinfo/gridpp-dirac-users

Regards,
Simon

**Comment by afortiorama** [comment]
This is the same error I reported on gridpp-ops. It happens when I submit with ganga not when I use the command line

aforti@vm7>dirac-wms-job-status 182662
JobID=182662 Status=Waiting; MinorStatus=Pilot Agent Submission; Site=LCG.UKI-LT2-Brunel.uk;

since Steve is not using ganga though but the Dirac API it is possible that the problem is in the API.

**Comment by afortiorama** [comment]
Actually forget what I said. It works also with ganga now, so it is the ce being dropped in Dirac.

899 | submitted |      test |         |     Executable |          Dirac |                        LCG.UKI-LT2-Brunel.uk |

**Comment by marianne013** [comment]
Hi Alessandra,

yes, we put in a temporary fix (it was a problem with the Brunel config), so it now works with the API. It was a bit confusing though, as Andrew's test jobs seem to work, I guess dirac is  more forgiving when using a jdl. 

Daniela

**Comment by sllloyd** [comment]
Yes it works now - thanks.
