### ISSUE TITLE
Problem submitting a sandbox with a whitespace in the name

### ISSUE THREAD

**Issue by rob-c** [ic-hep/DIRAC#67]
I've attached a short script highlighting the problem I'm seeing with submitting sandboxes with a whitespace in their full path.

This bug presents itself when submitting a job to the ic-hep instance of DIRAC.

I get a not-valid error when submitting using LHCbDirac but I get a different error which looks like vanilla DIRAC attempts to sanitize the filename into 2 different files around the whitespace (which obviously don't exist).

I don't know what the most appropriate solution to this would be but I've introduced a check and workaround in Ganga for 6.3 which should remove this as a potential problem for Ganga users.

(Apologies if this is a well known limitation but it caught us on Ganga by surprise)

[DIRAC_bug.zip](https://github.com/ic-hep/DIRAC/files/482617/DIRAC_bug.zip)

**Comment by sfayer** [comment]
Hi Rob,

I think this is the expected, but possibly undocumented, behaviour. Vanilla DIRAC assumes that any string with a space is a list of files rather than a file with a space. I don't think there is any easy way to override this. As this would be an API behaviour change, you'd need to open a ticket upstream if you would like to ask about the possibility of changing it (although I guess you're not really looking at this any more).

Regards,
Simon
