### ISSUE TITLE
"None" in MaxCPUTime and related fields should be treated as 0 

### ISSUE THREAD

**Issue by marianne013** [ic-hep/DIRAC#83]
Yesterday the Sitedirectors failed with an error casting None to a float. The matching error in the 
AutoBdii2CSAgent was:

2017-05-29 20:05:27 UTC Configuration/AutoBdii2CSAgent NOTICE: Setting /Resources/Sites/LCG/LCG.CERN-PROD.ch/CEs/ce503.cern.ch/Queues\
/ce503.cern.ch-condor/VO:   -> alice, atlas, cms, dteam, dune, envirogrids.vo.eu-egee.org, geant4, ilc, lhcb, ops, vo.aleph.cern.ch, \
vo.compass.cern.ch, vo.delphi.cern.ch, vo.gear.cern.ch, vo.l3.cern.ch, vo.opal.cern.ch, vo.sixt.cern.ch
2017-05-29 20:05:27 UTC Configuration/AutoBdii2CSAgent NOTICE: Setting /Resources/Sites/LCG/LCG.CERN-PROD.ch/CEs/ce503.cern.ch/Queues\
/ce503.cern.ch-condor/SI00:   -> 3100
2017-05-29 20:05:27 UTC Configuration/AutoBdii2CSAgent NOTICE: Setting /Resources/Sites/LCG/LCG.CERN-PROD.ch/CEs/ce503.cern.ch/Queues\
/ce503.cern.ch-condor/maxCPUTime:   -> None

(CERN apparently just added dune...)

In cases like this, the value should be set to 0, as it is unlikely that this queue will be usable.

**Comment by alexanderrichards** [comment]
@marianne013 , @sfayer We already have the following if the BDII is returning `'0'` for MaxCPUTime. 
```python
if max_cpu_time == "0":
    # bug on arc, hard code to 2 days
    max_cpu_time = "2880"
```
However as you rightly point out the problem is when it's `None`. Now I can default the value to 0 in case of None but in that case the above conditional will trigger the MaxCPUTime to be set to 2880. Is this desired or do we actually want it 0 in the None case?
